name: condas
channels:
  - defaults
  - conda-forge
  - conda-canary
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blinker=1.9.0=py311h06a4308_1
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.01.04=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - click=8.3.1=pyh8f84b5b_1
  - expat=2.7.4=h7354ed3_0
  - flask=3.1.2=py311h06a4308_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=py311h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jansson=2.15.0=h280c20c_0
  - jinja2=3.1.6=pyhcf101f3_1
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgomp=15.2.0=he0feb66_17
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libuuid=2.41.3=h5347b49_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=py311h3778330_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hd63d673_3_cpython
  - python-dotenv=1.2.1=py311h06a4308_0
  - python_abi=3.11=8_cp311
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - segno=1.6.6=pyhd8ed1ab_0
  - setuptools=82.0.0=pyh332efcf_0
  - sqlite=3.51.2=h04a0ce9_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=py311h06a4308_0
  - uwsgi=2.0.31=py311h3d26143_2
  - waitress=3.0.2=pyhcf101f3_2
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/dinamitrii/anaconda3/envs/condas
