name: condas
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blinker=1.9.0=py311h06a4308_1
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - click=8.2.1=py311h06a4308_1
  - expat=2.7.4=h7354ed3_0
  - flask=3.1.2=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - importlib-metadata=8.7.0=py311h06a4308_0
  - itsdangerous=2.2.0=py311h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=py311h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - markupsafe=3.0.2=py311h5eee18b_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py311h06a4308_1
  - pcre=8.45=h295c915_0
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - python-dotenv=1.2.1=py311h06a4308_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - segno=1.6.6=pyhd8ed1ab_0
  - setuptools=80.10.2=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py311h06a4308_0
  - uwsgi=2.0.21=py311h32d3c7e_4
  - waitress=3.0.2=py311h06a4308_0
  - werkzeug=3.1.3=py311h06a4308_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.23.0=py311h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
prefix: /home/dinamitrii/anaconda3/envs/condas
